#include <nds.h>

#include "gl2d.h"
#include "graphics/fontHandler.h"

#include "buttons.h"

typedef struct rvidHeaderInfo {
	u32 formatString;	// "RVID" string
	u32 ver;			// File format version
	u32 frames;			// Number of frames
	u8 fps;				// Frames per second
	u8 vRes;			// Vertical resolution
} rvidHeaderInfo;

extern rvidHeaderInfo rvidHeader;
extern bool videoPlaying;
extern int currentFrame;

extern char timeStamp[32];

static int buttonTexID;

static glImage buttonImage[(128 / 32) * (128 / 64)];

void loadGraphics(void) {
	buttonTexID = glLoadTileSet(buttonImage, // pointer to glImage array
							128, // sprite width
							64, // sprite height
							128, // bitmap width
							128, // bitmap height
							GL_RGB16, // texture type for glTexImage2D() in videoGL.h
							TEXTURE_SIZE_128, // sizeX for glTexImage2D() in videoGL.h
							TEXTURE_SIZE_128, // sizeY for glTexImage2D() in videoGL.h
							TEXGEN_OFF | GL_TEXTURE_COLOR0_TRANSPARENT, // param for glTexImage2D() in videoGL.h
							16, // Length of the palette to use (16 colors)
							(u16*) buttonsPal, // Load our 16 color tiles palette
							(u8*) buttonsBitmap // image data generated by GRIT
							);

	fontInit();
}

void renderGui(void) {
	clearText(false);
	printSmallCentered(false, 120, timeStamp);

	glBegin2D();
	{
		glBoxFilled(0, 0, 255, 191, RGB15(255/8, 255/8, 255/8));		// BG
		glBoxFilled(0, 0, 255, 59, RGB15(0/8, 176/8, 248/8));			// Title bar
		glBoxFilled(0, 58, 255, 58, RGB15(160/8, 224/8, 248/8));		// Title bar edge
		glBoxFilled(0, 160, 255, 191, RGB15(184/8, 184/8, 184/8));	// Bottom gray bar
		glBoxFilled(14, 142, 241, 145, RGB15(152/8, 152/8, 152/8));	// Play bar horizontal edge
		glBoxFilled(15, 141, 240, 146, RGB15(152/8, 152/8, 152/8));	// Play bar mid edge
		glBoxFilled(16, 140, 239, 147, RGB15(152/8, 152/8, 152/8));	// Play bar vertical edge
		glBoxFilled(16, 142, 239, 145, RGB15(255/8, 255/8, 255/8));	// Behind gray part of play bar
		/*
		glBoxFilled(4+(currentFrame/(rvidHeader.frames/184)), 142, 247, 145, RGB15(96/8, 96/8, 96/8));	// Gray part of play bar
		glBoxFilled(12+(currentFrame/(rvidHeader.frames/184)), 134, 19+(currentFrame/(rvidHeader.frames/184)), 153, RGB15(120/8, 120/8, 120/8));	// Play bar slider edge
		glBoxFilled(14+(currentFrame/(rvidHeader.frames/184)), 136, 17+(currentFrame/(rvidHeader.frames/184)), 151, RGB15(255/8, 255/8, 255/8));	// Play bar slider
		glBoxFilled(14+(currentFrame/(rvidHeader.frames/184)), 148, 17+(currentFrame/(rvidHeader.frames/184)), 151, RGB15(216/8, 216/8, 216/8));	// Play bar slider shading
		*/

		glSprite(73, 76, GL_FLIP_NONE, &buttonImage[videoPlaying]);

		updateText(false);
		glColor(RGB15(31, 31, 31));
	}
	glEnd2D();
	GFX_FLUSH = 0;
}
